import sys
from datetime import date, datetime
from unittest.mock import MagicMock
import pytest
import sqlite3

# Mock macOS-specific modules before importing obsidian_ai_hub to prevent ModuleNotFoundError on Linux/CI
mock_modules = {
    "EventKit": MagicMock(),
    "AppKit": MagicMock(),
    "objc": MagicMock(),
    "Foundation": MagicMock(),
    "ApplicationServices": MagicMock(),
    "atomacos": MagicMock(),
    "Quartz": MagicMock(),
    "Vision": MagicMock(),
    "Cocoa": MagicMock(),
}
for name, m in mock_modules.items():
    sys.modules[name] = m

from obsidian_ai_hub import memory
from obsidian_ai_hub.activity import store


def test_activity_logs_migration_and_index(test_memory_db_path):
    conn = memory.get_db_connection()
    try:
        cursor = conn.cursor()
        cursor.execute("PRAGMA user_version;")
        assert cursor.fetchone()[0] == 4

        cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='activity_logs';")
        assert cursor.fetchone() is not None

        cursor.execute("SELECT name FROM sqlite_master WHERE type='index' AND name='idx_activity_logs_date_occurred';")
        assert cursor.fetchone() is not None
    finally:
        conn.close()


def test_add_and_get_activities_by_date(test_memory_db_path):
    conn = memory.get_db_connection()
    try:
        # Add first activity
        act1 = store.add_activity(
            conn=conn,
            activity_date="2026-07-20",
            occurred_at="2026-07-20T10:00:00",
            app_name="Safari",
            window_title="Google",
            summary="Searching stuff",
            category="調査・リサーチ",
            keywords=["search", "google"],
            screenshots=["/path/to/shot1.png"],
        )

        # Assert autogenerated ID and other fields
        assert act1["activity_id"].startswith("act_")
        assert act1["activity_date"] == "2026-07-20"
        assert act1["keywords"] == ["search", "google"]
        assert act1["screenshots"] == ["/path/to/shot1.png"]

        # Add second activity slightly later
        act2 = store.add_activity(
            conn=conn,
            activity_date="2026-07-20",
            occurred_at="2026-07-20T11:00:00",
            app_name="VS Code",
            window_title="store.py",
            summary="Coding",
            category="開発",
            keywords=["python", "coding"],
            screenshots=[],
        )

        # Add third activity for a different date
        store.add_activity(
            conn=conn,
            activity_date="2026-07-21",
            occurred_at="2026-07-21T09:00:00",
            app_name="Slack",
            window_title="general",
            summary="Chatting",
            category="コミュニケーション",
        )

        # Get activities by date
        acts = store.get_activities_by_date("2026-07-20", conn=conn)
        assert len(acts) == 2
        # Check sorting by occurred_at ASC
        assert acts[0]["activity_id"] == act1["activity_id"]
        assert acts[1]["activity_id"] == act2["activity_id"]

        assert acts[0]["keywords"] == ["search", "google"]
        assert acts[1]["keywords"] == ["python", "coding"]
        assert acts[0]["screenshots"] == ["/path/to/shot1.png"]
        assert acts[1]["screenshots"] == []

        # Get latest activity by date
        latest = store.get_latest_activity_by_date("2026-07-20", conn=conn)
        assert latest is not None
        assert latest["activity_id"] == act2["activity_id"]

        # Non-existent date
        none_acts = store.get_activities_by_date("2026-07-19", conn=conn)
        assert len(none_acts) == 0

        none_latest = store.get_latest_activity_by_date("2026-07-19", conn=conn)
        assert none_latest is None
    finally:
        conn.close()


def test_get_recent_activities(test_memory_db_path):
    conn = memory.get_db_connection()
    try:
        # Base date is 2026-07-22
        # Activities on 2026-07-22 (today)
        store.add_activity(
            conn=conn,
            activity_date="2026-07-22",
            occurred_at="2026-07-22T10:00:00",
            summary="Active today",
        )

        # Activities on 2026-07-21 (yesterday)
        store.add_activity(
            conn=conn,
            activity_date="2026-07-21",
            occurred_at="2026-07-21T08:00:00",
            summary="Active yesterday",
        )

        # Activities with empty summary (should be excluded)
        store.add_activity(
            conn=conn,
            activity_date="2026-07-21",
            occurred_at="2026-07-21T09:00:00",
            summary="",
        )
        store.add_activity(
            conn=conn,
            activity_date="2026-07-21",
            occurred_at="2026-07-21T10:00:00",
            summary="   ",
        )
        store.add_activity(
            conn=conn,
            activity_date="2026-07-21",
            occurred_at="2026-07-21T11:00:00",
            summary=None,
        )

        # Activity 3 days ago (2026-07-19)
        store.add_activity(
            conn=conn,
            activity_date="2026-07-19",
            occurred_at="2026-07-19T15:00:00",
            summary="Active three days ago",
        )

        # Activity outside window (4 days ago: 2026-07-18)
        store.add_activity(
            conn=conn,
            activity_date="2026-07-18",
            occurred_at="2026-07-18T12:00:00",
            summary="Outside range",
        )

        # Query recent activities with days=3 (22, 21, 20)
        recent = store.get_recent_activities(
            days=3,
            base_date=date(2026, 7, 22),
            conn=conn,
        )

        # Expected: "Active today", "Active yesterday"
        # Three days ago (19) and outside range (18) are excluded
        # Empty/whitespace/None summaries are excluded
        assert len(recent) == 2
        assert recent[0]["summary"] == "Active today"
        assert recent[1]["summary"] == "Active yesterday"

        # Query with days=4 (22, 21, 20, 19)
        recent_four = store.get_recent_activities(
            days=4,
            base_date=date(2026, 7, 22),
            conn=conn,
        )
        assert len(recent_four) == 3
        assert recent_four[0]["summary"] == "Active today"
        assert recent_four[1]["summary"] == "Active yesterday"
        assert recent_four[2]["summary"] == "Active three days ago"
    finally:
        conn.close()


def test_unique_source_path_and_line_constraint(test_memory_db_path):
    conn = memory.get_db_connection()
    try:
        # Multiple NULL/None source_path and line should succeed
        store.add_activity(conn=conn, source_path=None, source_line=None)
        store.add_activity(conn=conn, source_path=None, source_line=None)

        # Specifying a source_path and line
        store.add_activity(conn=conn, source_path="log.jsonl", source_line=5)

        # Adding same combination should raise sqlite3.IntegrityError
        with pytest.raises(sqlite3.IntegrityError):
            store.add_activity(conn=conn, source_path="log.jsonl", source_line=5)
    finally:
        conn.close()


def test_no_conn_specified(test_memory_db_path):
    # This test verifies that store functions successfully obtain and close their own connections if not provided.
    act = store.add_activity(
        activity_date="2026-07-25",
        occurred_at="2026-07-25T12:00:00",
        summary="Self-contained connection",
    )
    assert act["activity_id"].startswith("act_")

    acts = store.get_activities_by_date("2026-07-25")
    assert len(acts) == 1
    assert acts[0]["summary"] == "Self-contained connection"

    latest = store.get_latest_activity_by_date("2026-07-25")
    assert latest is not None
    assert latest["summary"] == "Self-contained connection"

    recent = store.get_recent_activities(days=1, base_date=date(2026, 7, 25))
    assert len(recent) == 1
    assert recent[0]["summary"] == "Self-contained connection"
