export const ROUTES = {
  MEMORIES: "/memories",
  RESEARCH: "/research",
  AGENTS: "/agents",
  CODING: "/coding",
  VAULT_SEARCH: "/vault-search",
  SUMMARY_DASHBOARD: "/summary-dashboard",
  HEALTHCARE: "/healthcare",
  PEOPLE: "/people",
  PROJECTS: "/projects",
  TASKS: "/tasks",
  EXECUTION_LOGS: "/execution-logs",
  HITL: "/hitl",
  PLANNER: "/planner",
  SETTINGS: "/settings",
} as const;
